site_name: 'ARCTIc'
theme:
  name: 'material'
  font:
    text: Open Sans
    code: Courier New
  icon:
    admonition:
  features:
    - content.footnote.tooltips
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
extra_javascript:
  - assets/javascripts/mathjax.js
  - assets/javascripts/char-replacement.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - assets/stylesheets/fonts.css